---
title: "R Notebook"
output: html_notebook
---

Use readxl to read spreadsheet data.

```{r}
library(readxl)
library(readr)
library(dplyr)
library(tidyr)
library(fuzzyjoin)
library(stringr)
alma <- read_excel("data/URI-ALMA-QA-04082019.xlsx", skip = 2)
names(alma) <- c("title", "lcclass", "pubdate", "publisher", "physitem", "lang")

maa <- read_excel("data/BLL_Feb_1_2018.xlsx", skip = 1)
names(maa) <- c("title",	"author",	"edition",	"publisher",	"pubyear",	"rating",	"topics")

```

Create a match title function to implement a fuzzy join using stringdist_join.  
**To do**  
- Do additional test on cases with pubmatch == 1 to look for a match at the beginning of the title, i.e. str_locate("foobar", "foo")

```{r}

matchtitles <- function(x = maa, y = alma, yr=2019) {
  y <- y %>% 
    mutate(pubyear = parse_number(pubdate)) %>%
    mutate(title = str_replace(title, "\\s*/$", "")) %>% # remove trailing "/"
    mutate(cleantitle = gsub("\\s*[:punct:]\\s+", " ", gsub("^An{0,1}\\s+", "", title))) %>% 
    filter(pubyear == yr)

  x <- x %>%
    mutate(cleantitle = gsub("\\s*[:punct:]\\s+", " ", gsub("^An{0,1}\\s+", "", title))) %>%
    filter(pubyear == yr)
  
  matches <- stringdist_join(x, y, 
                by = "cleantitle",
                mode = "left",
                ignore_case = TRUE, 
                method = "jw", 
                max_dist = 99, 
                distance_col = "dist") %>%
    select(title.x, title.y, dist, publisher.x, publisher.y, rating, topics) %>%
    arrange(title.x, dist) %>%
    group_by(title.x) %>%
    summarize(score = first(dist),
            title.y = first(title.y),
            publisher.x = first(publisher.x),
            publisher.y = first(publisher.y),
            rating = first(rating),
            topics = first(topics)) %>%
    mutate(pubmatch = ifelse(str_detect(publisher.x,publisher.y) |
                              str_detect(publisher.y,publisher.x), 1, 0),
           partialmatch = ifelse(grepl(paste("^",tolower(title.x),sep=""), tolower(title.y)) |
                                  grepl(paste("^",tolower(title.y),sep=""), tolower(title.x)), 1, 0)) %>%
    arrange(desc(score)) %>%
    filter(score > .1) 
  return(matches)  
}

```

**To do**  
- Use a loop to run thru all the years
- Merge with the maa list and create a buy list (by year)
```{r}
#pre2000 <- matchtitles(maa, alma, 2000)
for (yr in 2000:2018) {
  df <- matchtitles(maa, alma, yr)
}
df2005 <- matchtitles(maa, alma, 2005)
df2006 <- matchtitles(maa, alma, 2006)
df2007 <- matchtitles(maa, alma, 2007)
df2008 <- matchtitles(maa, alma, 2008)
df2009 <- matchtitles(maa, alma, 2009)
df2010 <- matchtitles(maa, alma, 2010)
df2011 <- matchtitles(maa, alma, 2011)
df2012 <- matchtitles(maa, alma, 2012)
df2013 <- matchtitles(maa, alma, 2013)
df2014 <- matchtitles(maa, alma, 2014)
df2015 <- matchtitles(maa, alma, 2015)
df2016 <- matchtitles(maa, alma, 2016)
df2017 <- matchtitles(maa, alma, 2017)
df2018 <- matchtitles(maa, alma, 2018)
```

```{r}
review <- matches %>% 
  select(title.x, title.y, dist, publisher.x, publisher.y, rating, topics) %>%
  arrange(title.x, dist) %>%
  group_by(title.x) %>%
  summarize(score = first(dist),
            title.y = first(title.y),
            publisher.x = first(publisher.x),
            publisher.y = first(publisher.y),
            rating = first(rating),
            topics = first(topics)) %>%
  arrange(desc(score))
```

